version: '3.7'

services:
  # Serviço da aplicação Go
  app:
    build:
      context: ./app
    container_name: gotham_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
      - APP_PORT=${APP_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - gotham_network

  # Serviço do Postgres
  postgres:
    image: postgres:13
    container_name: gotham_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotham_network

  # Serviço do Redis
  redis:
    image: redis:6
    container_name: gotham_redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - gotham_network

networks:
  gotham_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
