FROM golang:1.23

# Criar usuário não-root
RUN useradd -r -u 1001 -g root appuser

WORKDIR /app

COPY . .

RUN go mod download && \
    go mod tidy && \
    go build -o app ./cmd/gotham/main.go && \
    chown -R appuser:root /app

USER appuser

EXPOSE 8000

CMD ["./app"] 