version: '3.7'

services:
  # Serviço da aplicação Go
  gotham:
    build: .
    container_name: gotham_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      gotham_network:
        ipv4_address: 172.28.0.2

  # Serviço do Postgres
  postgres:
    image: postgres:13
    container_name: gotham_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      gotham_network:
        ipv4_address: 172.28.0.3

  # Serviço do Redis
  redis:
    image: redis:6
    container_name: gotham_redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: always
    networks:
      gotham_network:
        ipv4_address: 172.28.0.4

networks:
  gotham_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"

volumes:
  postgres_data:
    driver: local
