version: '3.7'

services:
  # Serviço da aplicação Go
  app:
    build: ./
    container_name: gotham_app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - gotham_network

  # Serviço do Postgres
  postgres:
    image: postgres:13
    container_name: gotham_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotham_network

  # Serviço do Redis
  redis:
    image: redis:6
    container_name: gotham_redis
    env_file: 
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - gotham_network

networks:
  gotham_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
