basePath: /api/v1
definitions:
  models.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.PaginatedResponse:
    properties:
      current_page:
        type: integer
      data: {}
      limit:
        type: integer
      message:
        type: string
      status:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  models.Permission:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  models.Role:
    properties:
      id:
        type: integer
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/models.Permission'
        type: array
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/models.Role'
      roleID:
        type: integer
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: jefferson.developers@gmail.com
    name: Jefferson Martins
    url: https://www.linkedin.com/in/jefferson-martins-a6802b249/
  description: API para gerenciamento de usuários e autenticação
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Gotham API
  version: 1.0.0
paths:
  /admin/users/{id}:
    delete:
      description: Exclui um usuário com base no ID fornecido
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Usuário excluído com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: ID inválido
          schema:
            type: string
        "500":
          description: Erro ao excluir usuário
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Remove um usuário pelo ID
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um usuário com base no ID fornecido
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do usuário a serem atualizados
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: Usuário atualizado com sucesso
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: ID ou dados inválidos
          schema:
            type: string
        "404":
          description: Usuário não encontrado
          schema:
            type: string
        "500":
          description: Erro ao atualizar usuário
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Atualiza as informações de um usuário
  /login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e gera um token JWT
      parameters:
      - description: Credenciais do usuário
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token gerado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Dados inválidos
          schema:
            type: string
        "401":
          description: Usuário não encontrado ou senha incorreta
          schema:
            type: string
      summary: Login do usuário
  /protected/tasks:
    get:
      description: Obtém uma lista de tarefas fictícias para a demonstração
      produces:
      - application/json
      responses:
        "200":
          description: Lista de tarefas
          schema:
            items:
              additionalProperties:
                type: string
              type: object
            type: array
      security:
      - BearerAuth: []
      summary: Retorna uma lista de tarefas
  /refresh_token:
    post:
      consumes:
      - application/json
      description: Gera um novo token JWT quando fornecido um refresh token válido
      parameters:
      - description: Refresh Token
        in: body
        name: refreshRequest
        required: true
        schema:
          $ref: '#/definitions/models.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Novo token gerado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Dados inválidos
          schema:
            type: string
        "401":
          description: Refresh token inválido
          schema:
            type: string
        "404":
          description: Usuário não encontrado
          schema:
            type: string
      summary: Gera um novo token JWT usando o refresh token
  /users:
    get:
      consumes:
      - application/json
      description: Retorna uma lista paginada de todos os usuários
      parameters:
      - default: 1
        description: Número da página
        in: query
        name: page
        type: integer
      - default: 10
        description: Itens por página
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedResponse'
        "500":
          description: Erro ao contar usuários
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Lista todos os usuários
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Cria um novo usuário no sistema com os dados fornecidos
      parameters:
      - description: Dados do novo usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário criado com sucesso
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Dados inválidos
          schema:
            type: string
        "500":
          description: Erro ao criar usuário
          schema:
            type: string
      summary: Cria um novo usuário
  /users/{id}:
    get:
      description: Obtém um usuário específico com base no ID fornecido
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Usuário encontrado
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: ID inválido
          schema:
            type: string
        "404":
          description: Usuário não encontrado
          schema:
            type: string
      summary: Retorna um usuário pelo ID
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Operações relacionadas a usuários
  name: users
- description: Operações de autenticação
  name: auth
